### PR TITLE
Update Sinope_TH1124ZB.md

### PR DESCRIPTION
**Pull request by BabaIsYou**
Adding information for Ouellet thermostat oth4000-zb that is manufactured by Sinopé

### CODE REVIEW

**Comment by blakadder** [comment]
Nope, that's a new device so it needs a new file

**Comment by BabaIsYou** [comment]
I already submitted it last week … ;-)

Le 28 oct. 2022 à 18:35, blakadder ***@***.***> a écrit :

﻿

Nope, that's a new device so it needs a new file

**Comment by BabaIsYou** [comment]
Completly agree. Already submitted it as a new device using website form last week ;-)

Without answer I thought that it was rejected.

May I have to submit it again ?

Le 28 oct. 2022 à 19:33, Baba Is You ***@***.***> a écrit :

﻿
I already submitted it last week … ;-)

Le 28 oct. 2022 à 18:35, blakadder ***@***.***> a écrit :

﻿

Nope, that's a new device so it needs a new file

**Comment by blakadder** [comment]
its added from the submitted form

**Pull request closed without merging**
