### PR TITLE
Update coordinator_RaspBee_II.md with a description

### PR DESCRIPTION
**Pull request by Hedda**
Update coordinator_RaspBee_II.md with a description

### CODE REVIEW

**Comment by blakadder** [comment]
Raspbee II is not listed as supported on the ZHA page. Do you own a RaspBee II working with ZHA?

**Comment by Hedda** [comment]
Yes, RaspBee II has same chip as ConBee II just as first-gen RaspBee use same chip as first-gen ConBee.

I will do seperate PR for zigpy and zha readme files so that they too list RaspBee II.

* https://github.com/zigpy/zigpy/
* https://www.home-assistant.io/integrations/zha/

**Comment by Hedda** [comment]
https://github.com/zigpy/zigpy/pull/415

**Comment by Hedda** [comment]
https://github.com/home-assistant/home-assistant.io/pull/13440

**Comment by Hedda** [comment]
Both those upstream, PR have now been merged so "RaspBee II" is listed as supported by the projects:

- https://www.home-assistant.io/integrations/zha/

- https://github.com/zigpy/zigpy/blob/dev/README.md

**Comment by Hedda** [comment]
As per https://github.com/blakadder/zigbee/pull/33

Should update Phoscon_RaspBee_II.md with description plus corrected their product and brand names:

RaspBee product is written as "RaspBee" with a capital "R" and capital "B". Also, dresden elektronik officially write their company name in all lower case letters.

* https://www.dresden-elektronik.com/contact.html

dresden_elektronik_logo_small

"Phoscon" is only dresden elektronik own Zigbee gateway software and is not really part of the "ConBee" or "RaspBee" product names. The only reason to include the name "Phoscon" is when specifically referring to using ConBee or RaspBee in their new Phoscon Gateway software package.

* https://www.dresden-elektronik.com/wireless/software/deconz.html**
* https://phoscon.de/en/conbee2/software

To be more precise, Phoscon Gateway is their names for their Linux based operating system distro for Raspberry Pi and it turns runs their deCONZ gateway software) or its Phoscon App for iOS and Android mobiles.

ConBee and Raspbee are also sold as stand-alone products withouth the Phoscon Gateway SW

* https://www.dresden-elektronik.com/product/raspbee-II.html
* https://www.dresden-elektronik.com/product/conbee-2.html
* https://www.dresden-elektronik.com/product/phoscon-gateway.html

That is why the products are listed on both sites:

* https://phoscon.de/en/raspbee2
* https://phoscon.de/en/conbee2
* https://phoscon.de/en/conbee
* https://phoscon.de/en/raspbee

Note that while not part of this PR, suggest that you should really rename those files to either only us their ConBee/RaspBee product names or named with "dresden_elektronik_productname" (so company name as prefix, just without with "Phoscon" as it has nothing to do with the ConBee or RaspBee product names:

 Phoscon_Conbee_II.md -> Conbee_II.md
 Phoscon_RaspBee.md -> RaspBee.md
 Phoscon_RaspBee_II.md -> RaspBee_II

or 

 Phoscon_Conbee_II.md -> dresden_elektronik_Conbee_II.md
 Phoscon_RaspBee.md -> dresden_elektronik_RaspBee.md
 Phoscon_RaspBee_II.md -> dresden_elektronik_RaspBee_II

Here is a picture of ConBee II product package which clearly does not show the name Phoscon:

ConBee_II_product_package

**Comment by Hedda** [comment]
@blakadder Closed without comment?

**Comment by blakadder** [comment]
yes

**Comment by Hedda** [comment]
Hmm, I was not trying to be rude, however, I have OCD and know I might come off as annoying, but I think that closing without comment can definitely be seen as rude. Better to just ignore if that is the case.

**Pull request closed without merging**
