### PR TITLE
Add SLS zigbee gateway.

### PR DESCRIPTION
**Pull request by directman66**

### CODE REVIEW

**Comment by blakadder** [comment]
I don't know what that is and it cannot be added just like that

**Comment by directman66** [comment]
Hello! Please tell me how to add your project to this directory?

Description of project https://slsys.github.io/Gateway/

**Comment by blakadder** [comment]
I've looked into it and it doesn't fit the criteria for inclusion yet

**Comment by directman66** [comment]
What should be the criteria for inclusion?

**Comment by blakadder** [comment]
- wider adoption  with smart home systems and global reach
- english documentation without missing links. 90% of your integration links are missing
- since it uses mqtt it looks just like a zigbee2mqtt remix

**Comment by directman66** [comment]
This is a hardware project, for compatibility with most automation systems a protocol compatible with zigbee2mkqq is used. This is not a fork of it.

**Comment by directman66** [comment]
After adding the links in English, will it be possible to add our project to your catalog?

**Comment by blakadder** [comment]
no, sorry. size of the project doesn't justify the time required to add it to the site and maintain information

**Comment by directman66** [comment]
Good evening. It seems that our SLS gateway project has already gained some popularity in foreign resources. Do you want to add support for our gateway to your catalog?  https://github.com/slsys/Gateway SLS Zigbee Gateway https://www.reddit.com/r/homeassistant/comments/fwulqe/sls_zigbee_gateway_a_new_zigbee_gateway_based_on/   02.03.2020, 14:08, "blakadder" <notifications@github.com>:no, sorry. size of the project doesn't justify the time required to add it to the site and maintain information—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- Good afternoon.  ___________________________________Sincerely, Dmitry Igorevich Sannikov.

**Comment by directman66** [comment]
Good evening. It seems that our SLS gateway project has already gained some popularity in foreign resources. Do you want to add support for our gateway to your catalog?
 
 
https://github.com/slsys/Gateway
 
SLS Zigbee Gateway
 
https://www.reddit.com/r/homeassistant/comments/fwulqe/sls_zigbee_gateway_a_new_zigbee_gateway_based_on/

**Pull request closed without merging**
