### PR TITLE
Fix Sonoff_ZBBridge-P leds

### PR DESCRIPTION
**Pull request by shantur**
Update Template. This fixes the leds on Sonoff_ZBBridge-P

### CODE REVIEW

**Comment by blakadder** [comment]
no it doesn't

**Comment by shantur** [comment]
I just flashed a brand new Sonoff ZBBridge Pro and with the template on the website it doesn't turn on the LEDs.
I had to change Led_i ti Led in the template to make them work.

image

**Comment by blakadder** [comment]
The PR is empty. Changing the Led to Led_i just revert its behaviour. It's not "fixing" anything just makes it behave to your liking

**Comment by shantur** [comment]
Apologies, not sure why Github PR was empty even when I used web editor.
Is expectation for LEDs to be always off? The power LED never worked with LED_i.

**Pull request closed without merging**
