### PR TITLE
Create coordinator_ConBee.md for first-gen ConBee USB from dresden elektronik

### PR DESCRIPTION
**Pull request by Hedda**
Create coordinator_ConBee.md for first-generation ConBee USB from dresden elektronik.

PS: FYI, dresden elektronik offically write their company name in all lower case letters.

### CODE REVIEW

**Comment by blakadder** [comment]
the image is missing

**Comment by Hedda** [comment]
Sorry I don't have a good image myself. Also, I understand that this first-generation ConBee were available/sold in both black and white enclosures (with the same board inside), so which image to use?

**Comment by blakadder** [comment]
You're the one submitting, if they're not available anymore then there's no point in submitting it

**Comment by Hedda** [comment]
They are no longer being manufactured but they are being sold as resellers still have old stock. 

They still belong to in a compatibility list like this as my guess is also that this first-generation ConBee is probably the most sold and most commonly sold commercial Zigbee USB coordinator stick (with the most common non-commercial DYI Zigbee USB coordinator stick probably being C2530 and CC251 based).

**Comment by Hedda** [comment]
Copied image https://phoscon.de/conbee/img/conbee1_400px.jpg from https://phoscon.de/en/conbee

**Comment by Hedda** [comment]
Uploaded white version from https://www.amazon.de/ConBee-ZigBee-intelligente-moderne-Funkbeleuchtung/dp/B01FDWOIHK/

**Comment by blakadder** [comment]
added internally due to bad image format

**Pull request closed without merging**
