### PR TITLE
Update Rehent_RH-ZTH1.md

### PR DESCRIPTION
**Pull request by cornim**
Page not found

### CODE REVIEW

**Comment by blakadder** [comment]
works for me

**Comment by cornim** [comment]
Why do you write "works for me" but then close the PR without merging it?

Same for #770?

**Comment by cornim** [comment]
Ah, you're probably trying to say, that the link works for you, not the change.

**Comment by cornim** [comment]
I checked again and I still get a page not found. Probably a geo ip block then.

**Pull request closed without merging**
